name: muse_overlay
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - tk
  - pywin32
  - pip
  - pip:
    - pygame
    - pylsl
    - heartpy
    - seaborn
    - oscpy
    - python-osc
    - pywin32
    - keyboard
